#!/usr/bin/env python3
"""Generate checker dialects from canonical ST; --check never writes files."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

UNITS = [
    "FC_MainSequence_BusyPhase", "FC_MainSequence_InvalidPhase",
    "FC_MainSequence_StepDone", "FC_MainSequence_SuccessPhase",
    "FC_MainSequence_TimeoutReached", "FC_MainSequence_NextPhase",
    "FC_MainSequence_NextTimer", "FC_MainSequence_NextTimeoutFault",
    "FB_MainSequence",
]


def as_step7(source: str) -> str:
    """Only add Step7's BEGIN separator; expressions and constants stay intact."""
    sections = list(re.finditer(r"(?m)^END_VAR\s*$", source))
    if not sections:
        raise ValueError("source unit has no declaration section")
    pos = sections[-1].end()
    return source[:pos] + "\nBEGIN" + source[pos:]


def expected_files(project: Path) -> dict[Path, str]:
    sources = {name: (project / "02_src/st" / f"{name}.st").read_text()
               for name in UNITS}
    actual_names = {p.stem for p in (project / "02_src/st").glob("*.st")}
    if actual_names != set(UNITS):
        raise ValueError("source unit set changed; update explicit dependency order")
    assertions_path = project / "03_checks/plcverif/assertions.scl"
    assertions = assertions_path.read_text()
    if any(line.strip() and not line.lstrip().startswith("//")
           for line in assertions.splitlines()):
        raise ValueError("assertions.scl may contain comments/assertions only")
    formal = "\n".join(as_step7(sources[n]) for n in UNITS)
    formal = formal.replace("END_FUNCTION_BLOCK", assertions + "\nEND_FUNCTION_BLOCK")
    driver_path = project / "03_checks/openplc/driver.st"
    driver = driver_path.read_text()
    if not re.search(r"(?m)^PROGRAM PLC_PRG\b", driver):
        raise ValueError("OpenPLC driver is missing PLC_PRG")
    header = "(* Generated by validation/scripts/sync-semantics.py; edit 02_src/st. *)\n"
    files = {
        project / "03_checks/plcverif/FB_MainSequence_PLCverif.scl": header + formal,
        project / "03_checks/openplc/FB_MainSequence_OpenPLC.st":
            header + "\n".join(sources[n] for n in UNITS) + "\n" + driver,
    }
    for name, source in sources.items():
        files[project / "05_tia_sync/exported_scl" / f"{name}.st"] = source
    inputs = [project / "02_src/st" / f"{n}.st" for n in UNITS]
    inputs += [assertions_path, driver_path, project / "01_specs/scan-contract.md"]
    sha = lambda data: hashlib.sha256(data).hexdigest()
    manifest = {
        "schema_version": 1,
        "source_of_truth": "02_src/st",
        "formal_abstraction": "none; input timeout is not replaced by a constant",
        "siemens_final": "unverified",
        "generator_sha256": sha(Path(__file__).read_bytes()),
        "inputs": {str(p.relative_to(project)): sha(p.read_text().encode()) for p in inputs},
        "outputs": {str(p.relative_to(project)): sha(s.encode()) for p, s in files.items()},
    }
    files[project / "00_meta/projection-manifest.json"] = json.dumps(
        manifest, indent=2, ensure_ascii=False) + "\n"
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    try:
        expected = expected_files(args.project.resolve())
        stale = [p for p, content in expected.items()
                 if not p.exists() or p.read_text() != content]
        if args.write:
            for p in stale:
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(expected[p], newline="\n")
            print(f"Updated {len(stale)} generated files; Siemens final remains unverified")
            return 0
        for p in stale:
            print(f"STALE: {p}", file=sys.stderr)
        if not stale:
            print("PASS: all projections and source hashes match")
        return 1 if stale else 0
    except (OSError, ValueError) as exc:
        print(f"BLOCKED: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
